server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location /health {
        add_header Content-Type application/json;
        add_header Access-Control-Allow-Origin *;
        return 200 '{"status":"ok"}';
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
